### ISSUE TITLE
Private registry support: separate image repository from version and support for imagePullSecrets in Values.yaml

### ISSUE THREAD

**Issue by antoinetran** [interTwin-eu/interlink-helm-chart#15]
Issue:
When using private registry like Artifactory, which can be mandatory in some HPCs, InterLink Helm does not offer convenient way to implement private registry.

Currently:
1. imagePullSecrets is not supported
2. we cannot override images without overriding also the image version. It is a good practice to separate those. Eg: Argo helm separate a full image name (eg: `quay.io/argoproj/workflow-controller:0.1.2`) to three fields:
```
controller:
  image:
    registry: quay.io
    repository: argoproj/workflow-controller
    tag: "0.1.2"
```
(see https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L84)

Suggestion of solution:
1. separate each image to 3 image fields, and add a global registry in Values.yaml, that, if not empty, will override all image registry prefix.
2. add a imagePullSecrets array in Values.yaml (just a global level would be enough)
